### ISSUE TITLE
notes on highflowNEXT sensors presentation

### ISSUE THREAD

**Issue by dankamongmen** [aleksamagicka/aquacomputer_d5next-hwmon#33]
hey there from https://www.reddit.com/r/watercooling/comments/wr667q/comment/imagfkp/?context=3 ! =]

i went ahead and rebuilt `aquacomputer_d5next.ko` using this tree (i already had one built from mainline, which i copied over with the new module, after ensuring it was not loaded). the module loads fine, but it doesn't seem to provide any `hwmon` device in `/sys/class/hwmon`, nor do i see any new output in `sensors`, nor do i see any output in `dmesg`.

the device is connected and not being used:

```sh
[schwarzgerat](0) $ lsusb | grep -n -i flow
12:Bus 009 Device 008: ID 0c70:f012 MCT Elektronikladen high flow NEXT
[schwarzgerat](0) $ 
```

and i can verify by visual inspection that it is powered on and functioning as expected. i do not have the VISION sensor for external temperature installed at the moment, but it will be going on soon. currently only the usb cable is plugged into the device.

kernel is 5.19.5nlb2 (mainline + OpenRGB patches + my console patches for Notcurses). i can repeat on a bare mainline kernel, but i doubt very seriously that these patches are causing any problem.

let me know how i can assist! i'm very comfortable patching and building kernels and userspace, and pretty familiar with `hwmon`, so don't feel the need to explain much =].

**Comment by aleksamagicka** [comment]
Hi! 👋 

Stupid question, but perhaps you didn't compile the highflownext branch? The main one does not have the HFN code yet. Looking at the code, [it's listed](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/pull/18/files#diff-b0eeb47bb02c97a51a04cecf13c9b19ee9a4bbea5c45ad9ceee2afaba29dc51fR1179) with ID `f012`, and as far as I can see on first glance I didn't break anything 😄

**Comment by dankamongmen** [comment]
> Stupid question, but perhaps you didn't compile the highflownext branch? The main one does not have the HFN code yet. Looking at the code, [it's listed](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/pull/18/files#diff-b0eeb47bb02c97a51a04cecf13c9b19ee9a4bbea5c45ad9ceee2afaba29dc51fR1179) with ID `f012`, and as far as I can see on first glance I didn't break anything smile

you are absolutely correct; i read "branch" as repo in your post the other day. doh!

**Comment by dankamongmen** [comment]
> Stupid question, but perhaps you didn't compile the highflownext branch? The main one does not have the HFN code yet. Looking at the code, [it's listed](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/pull/18/files#diff-b0eeb47bb02c97a51a04cecf13c9b19ee9a4bbea5c45ad9ceee2afaba29dc51fR1179) with ID `f012`, and as far as I can see on first glance I didn't break anything smile

you are absolutely correct; i read "branch" as repo in your post the other day. doh!

**Comment by dankamongmen** [comment]
woohoo, can confirm new `/sys/class/hwmon19` with the branch's module loaded.

```
highflownext-hid-3-13
Adapter: HID adapter
+5V voltage:              4.72 V  
+5V USB voltage:          4.94 V  
Calibrated flow [dL/h]: 1613 RPM
Water quality [%]:      10000 RPM
Conductivity [nS/cm]:    320 RPM
Coolant temp:            +29.2°C  
External sensor:             N/A  
Power:                    0.00 W  
```

OH MY, HOW EXCITING!

let me hook up my VISION and see how that goes. this looks great!

**Comment by dankamongmen** [comment]
woohoo, can confirm new `/sys/class/hwmon19` with the branch's module loaded.

```
highflownext-hid-3-13
Adapter: HID adapter
+5V voltage:              4.72 V  
+5V USB voltage:          4.94 V  
Calibrated flow [dL/h]: 1613 RPM
Water quality [%]:      10000 RPM
Conductivity [nS/cm]:    320 RPM
Coolant temp:            +29.2°C  
External sensor:             N/A  
Power:                    0.00 W  
```

OH MY, HOW EXCITING!

let me hook up my VISION and see how that goes. this looks great!

does dL mean deciliter? it's not a derivative, surely?

**Comment by dankamongmen** [comment]
a few quick notes (i can put these in another issue):

* doesn't make sense to express water quality in RPM
* power requires the external sensor, right? it probably ought be N/A then if external sensor is N/A, rather than suggesting a valid 0 measurement
* what's the first +5V? the only power source here is USB
* "V" with "voltage" seems redundant imho

**Comment by dankamongmen** [comment]
also, as a note, if i've got a windows VM open running `AquacomputerService.exe` etc., loading the module succeeds but no device is found. not sure if that case can be detected, but probably worth a comment to the console if so.

**Comment by dankamongmen** [comment]
i'm showing 251.6 L/h steady on the device's display. how does that relate to this "1613 RPM" (likewise steady)? 

i guess according to https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface there's just the predefined types (power, current, fan, alert, intrusion, pwm, temp, for those playing at home). i guess `lm-sensors` userspace needs an update for each new type, huh? let me go look into how much pushback there is on new types. flow seems a type that ought be added IMHO.

**Comment by aleksamagicka** [comment]
1. RPM is pretty much the only way to show raw values through hwmon. That's why the unit is noted in the label.
2. dL means deciliter, yes.
3. I'm not sure about power, perhaps that's so but only you can test and say for sure :) Maybe the value is too small. The raw power value is being shown in debugfs, under the `serial_number` file (I didn't want to create a new entry at the time, since this is just for testing.)
4. The two +5V values are exposed in the HID report by the device, so we expose them here as well. I'm not sure as to why there are two, but they're different. Maybe that's some internal sanity check after a voltage drop or something, I don't design hardware so I'm not sure. It comes from [here](https://github.com/medevil84/FanControl.AquacomputerHighFlowNext).
5. "V" with voltage is just how `sensors` shows it.

**Comment by dankamongmen** [comment]
so we're showing `Water quality [%] 10000 RPM`. my sensor shows 100%. so i'm guessing that first off, the read needs to be scaled by dividing by 100. if it's a percent, maybe PWM rather than RPM?

**Comment by dankamongmen** [comment]
please don't hear this as criticism or anything btw -- i'm terribly excited to have access to my highflowNEXT; you're doing the Lord's work. just trying to polish as best i can =].

**Comment by aleksamagicka** [comment]
> i'm showing 251.6 L/h steady on the device's display. how does that relate to this "1613 RPM" (likewise steady)?
> 

Well, that does not seem right. It should read 2516 dL/h.

> i guess according to https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface there's just the predefined types (power, current, fan, alert, intrusion, pwm, temp, for those playing at home). i guess `lm-sensors` userspace needs an update for each new type, huh? let me go look into how much pushback there is on new types. flow seems a type that ought be added IMHO.

I'm pretty sure they won't expand, since marking it as a `fan` does the job. Then it's up to the driver docs and label to show what's happening. Otherwise, every driver would have it's own idea, and that's not something that would be accepted. In other words, tens of other drivers fit in the norm, and we're likely not special to make concessions for :)

**Comment by dankamongmen** [comment]
> > i'm showing 251.6 L/h steady on the device's display. how does that relate to this "1613 RPM" (likewise steady)?
> Well, that does not seem right. It should read 2516 dL/h.

ok looks like we have a bug there, then. my flow has been within 5L/h of 250L/h every time i've looked at it. `sensors` shows 1612 or 1613 every time. if you'd like, i can look into debugging this, or i can run experiments you spec. let me boot my windows VM and verify that Aquacomputer Suite is reporting the expected 250.

**Comment by aleksamagicka** [comment]
> so we're showing `Water quality [%] 10000 RPM`. my sensor shows 100%. so i'm guessing that first off, the read needs to be scaled by dividing by 100. if it's a percent, maybe PWM rather than RPM?

If we're not losing any decimal data by diving it by 100, I don't see why not. Does reading water quality require initial calibration through aquasuite? If so, that should be noted in the docs.

Marking it as PWM would mean that it goes from 0 to 255. Yes, we could scale it, but for what purpose? It's just a sensor. Plus, PWM stuff is usually writeable, which isn't the case here.

**Comment by aleksamagicka** [comment]
> please don't hear this as criticism or anything btw -- i'm terribly excited to have access to my highflowNEXT; you're doing the Lord's work. just trying to polish as best i can =].

Of course, I'd love to discuss everything regarding the driver.

**Comment by dankamongmen** [comment]
> Marking it as PWM would mean that it goes from 0 to 255. Yes, we could scale it, but for what purpose? It's just a sensor. Plus, PWM stuff is usually writeable, which isn't the case here.

i thought PWM was 0..99; if it's 0..255, my idea makes no sense whatsoever and ought be ignored =]

**Comment by dankamongmen** [comment]
> > so we're showing `Water quality [%] 10000 RPM`. my sensor shows 100%. so i'm guessing that first off, the read needs to be scaled by dividing by 100. if it's a percent, maybe PWM rather than RPM?
> 
> If we're not losing any decimal data by diving it by 100, I don't see why not. Does reading water quality require initial calibration through aquasuite? If so, that should be noted in the docs.

i mean if it's an int, we lose data; otherwise, we lose data only up through the vagueries of floating point. RPM looks to be an integer, whereas temp is a float. given that water quality is neither an RPM nor a temp, but temp reflects the floatiness of the percent, IMHO it would be best to divide it by 100 but report it as a temp, thus retaining data.

**Comment by dankamongmen** [comment]
> i mean if it's an int, we lose data; otherwise, we lose data only up through the vagueries of floating point. RPM looks to be an integer, whereas temp is a float. given that water quality is neither an RPM nor a temp, but temp reflects the floatiness of the percent, IMHO it would be best to divide it by 100 but report it as a temp, thus retaining data.

after all, calibrated or not, the sensor is displaying 100.00%, not 10000%

**Comment by aleksamagicka** [comment]
> > > i'm showing 251.6 L/h steady on the device's display. how does that relate to this "1613 RPM" (likewise steady)?
> > > Well, that does not seem right. It should read 2516 dL/h.
> 
> ok looks like we have a bug there, then. my flow has been within 5L/h of 250L/h every time i've looked at it. `sensors` shows 1612 or 1613 every time. if you'd like, i can look into debugging this, or i can run experiments you spec. let me boot my windows VM and verify that Aquacomputer Suite is reporting the expected 250.

I'd appreciate it! The HFN, as do other Aquacomputer devices, sends a HID report every second. You'd need to capture one of those and compare it with values shown in aquasuite in a hex editor. There you can find the flow value and see on what offset it is.

All data in the report is in big endian. I've seen people use wireshark, I've used [this](https://www.hhdsoftware.com/device-monitoring-studio) personally since I found it a bit easier to use at first, and stuck with it.

> > > so we're showing `Water quality [%] 10000 RPM`. my sensor shows 100%. so i'm guessing that first off, the read needs to be scaled by dividing by 100. if it's a percent, maybe PWM rather than RPM?
> > 
> > 
> > If we're not losing any decimal data by diving it by 100, I don't see why not. Does reading water quality require initial calibration through aquasuite? If so, that should be noted in the docs.
> 
> i mean if it's an int, we lose data; otherwise, we lose data only up through the vagueries of floating point. RPM looks to be an integer, whereas temp is a float. given that water quality is neither an RPM nor a temp, but temp reflects the floatiness of the percent, IMHO it would be best to divide it by 100 but report it as a temp, thus retaining data.

Temp is not a float internally, it's just shown as a float in the output. Internally, `25.6C` is `25600`. When I said losing data, I meant the last two digits, since in my experience it can happen that those are unused, and always stay `00`, so `9900`, `9800` etc.

We can't report is a temp either, it's certainly not in C. RPM is good enough when the label & docs specify what it is, and for water quality, I think dividing by 100 is not going to make a big difference anyway? Be it 99.4% or 99%, it would be clear what it is.

**Comment by dankamongmen** [comment]
> > ok looks like we have a bug there, then. my flow has been within 5L/h of 250L/h every time i've looked at it. `sensors` shows 1612 or 1613 every time. if you'd like, i can look into debugging this, or i can run experiments you spec. let me boot my windows VM and verify that Aquacomputer Suite is reporting the expected 250.
> 
> I'd appreciate it! The HFN, as do other Aquacomputer devices, sends a HID report every second. You'd need to capture one of those and compare it with values shown in aquasuite in a hex editor. There you can find the flow value and see on what offset it is.

yeah this isn't my first rodeo =]. i should be able to do that this weekend at the latest.

**Comment by aleksamagicka** [comment]
> > We can't report is a temp either, it's certainly not in C. RPM is good enough when the label & docs specify what it is, and for water quality, I think dividing by 100 is not going to make a big difference anyway? Be it 99.4% or 99%, it would be clear what it is.
> 
> .nodnod, all reasonable. i've not put much faith in that measure in any case =]. basically i just wanted to match the sensor's visual presentation by default in `sensors` output as closely as possible. it's not an issue of great importance, nor one where any option is much better than the others.
> 
> i'm kinda disappointed by the inflexibility of the hwmon API. i'm pondering extending it (in a backwards-compatible fashion) allowing the kernel drivers to pass down more information without complicating `sensors`. i might write that up and send it to LKML.

I doubt that any expansion would succeed - there's always debugfs if the driver needs to write arbitrary data and make it available to userspace. Anything other than that, the kernel is most likely not the place for that. The driver enables the hidraw interface so that user software can bypass it and interact with the device directly.

**Comment by dankamongmen** [comment]
with the VISION installed:

```
highflownext-hid-3-c
Adapter: HID adapter
+5V voltage:              4.73 V  
+5V USB voltage:          4.95 V  
Calibrated flow [dL/h]: 1611 RPM
Water quality [%]:      10000 RPM
Conductivity [nS/cm]:    340 RPM
Coolant temp:            +26.1°C  
External sensor:         +25.5°C  
Power:                  152.00 uW 
```

Power gets defined, as does External sensor, as expected.

Interestingly, I changed up my pump speeds, and flow is now significantly less than it was. `Calibrated flow`, however, still shows almost the same value (1611). anyway, i'll look into that as detailed above. have you seen `Calibrated flow` work with any other highflowNEXTs (if you've done any testing)?

**Comment by aleksamagicka** [comment]
> Power gets defined, as does External sensor, as expected.

Thanks for that. I'll rename `Power` to `External sensor power` or something similar, and make it return `N/A` if sensor temp is unavailable.

> Interestingly, I changed up my pump speeds, and flow is now significantly less than it was. Calibrated flow, however, still shows almost the same value (1611). anyway, i'll look into that as detailed above. have you seen Calibrated flow work with any other highflowNEXTs (if you've done any testing)?

Yes, we have one [here](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/issues/8#issuecomment-1182331160). `FlowCalibration` seems to fit well there. I don't have one myself. Looks like the flow [requires](https://i.gyazo.com/ee53d634c65e35a29c020a71f2ee327b.png) lots of things to be calibrated.

**Comment by dankamongmen** [comment]
> Thanks for that. I'll rename `Power` to `External sensor power` or something similar, and make it return `N/A` if sensor temp is unavailable.

ermmm "power" is definitely *not* external power. it's how much
power has been removed by the cooling solution, according to the
docs. i've never paid it much attention.

**Comment by aleksamagicka** [comment]
Hm, then I've misunderstood you. If I understand, it gets active when you plug in the VISION, which provides a temp sensor external to the HFN. What power does it represent? Do you mean the HFN docs so I can look it up?

**Comment by dankamongmen** [comment]
that is correct, and aye, the HFN user manual

**Comment by aleksamagicka** [comment]
Ah I see now, thanks. Does "absorbed power" or "dissipated power" sound good?

**Comment by dankamongmen** [comment]
i'd go with dissipated

**Comment by dankamongmen** [comment]
#34 resolves the flow display (wrong offset)

**Comment by dankamongmen** [comment]
i think we can close this up?

**Comment by aleksamagicka** [comment]
Yes, if anything arises just open a new issue.
