### ISSUE TITLE
highflownext "dissipated power" output is incorrect

### ISSUE THREAD

**Issue by dankamongmen** [aleksamagicka/aquacomputer_d5next-hwmon#35]
I'm seeing things in the micro and nanowatts, ala:

`Dissipated power:       231.00 uW`

i've always found this derived measurement a bit suspect, but this doesn't match what the device reports. i'll pull up the real value for contrast, and figure out what's going on. probably something like #34 where we just need a different offset.

fwiw, my UPS reports 666W of load =]. i'll get the device values from aquasuite in a VM.

**Comment by dankamongmen** [comment]
you can assign this to me, if you'd like

**Comment by dankamongmen** [comment]
alright, i watched this a little in my VM while running `stress-ng`. my observations:

* before beginning the stress-ng run, values were about 170--280W
* during running it, values ranged from 6W--280W
* my 3970X is rated for 280W without overclocking
* the value seemed to shrink towards 0 when External and Loop temp delta approached 0

for this to make any sense, you probably also need to know that before launching the stress test, my External was *above* my Loop, which is not supposed to happen, but is the case (maybe my External is near an exhaust)? so the delta was like:

-2deg
-1deg
0deg
1deg
....

and from what i can tell, the Dissipated Power has something to do with the absolute value of the delta. i'm honestly not sure why the device reports it at all, as it seems wholly derivable(?). i'm not completely understanding it, obviously.

BUT the upshot is that this ought be in W, and if it is, i *think* the value you're reporting will match that of the Aquasuite software. I'm seeing the value bounce around between about 30 and 170 uW right now, which would be reasonable if it was W (reasonable based on Aquasuite being the gold standard). running Aquasuite similarly saw the value bounce around a good deal.

**Comment by aleksamagicka** [comment]
So we can just convert uW to W and that should be good?

**Comment by dankamongmen** [comment]
so far as i understand!

**Comment by aleksamagicka** [comment]
OK, please try the latest commit, I think I got the right amount of zeroes.

**Comment by dankamongmen** [comment]
```
highflownext-hid-3-12
Adapter: HID adapter
+5V voltage:              4.70 V  
+5V USB voltage:          4.92 V  
Calibrated flow [dL/h]: 1868 RPM
Water quality [%]:      10000 RPM
Conductivity [nS/cm]:    325 RPM
Coolant temp:            +27.7°C  
External sensor:         +27.2°C  
Dissipated power:       108.00 W  
```

looking good!

**Comment by aleksamagicka** [comment]
Great, thank you so much for your help!
