### ISSUE TITLE
Predictable Sensor Name

### ISSUE THREAD

**Issue by projektdotnet** [aleksamagicka/aquacomputer_d5next-hwmon#40]
I'm not sure if this is a driver issue or an issue with lm-sensors but each time I reboot, the octo is assigned a different name (eg: octo-hid-3-11 and the next reboot it may be 3-10 or 3-12 instead). While this doesn't cause issue when using sensors in the command line, it does cause issues when trying to use the plasma thermal monitor because it's expecting the same source name each time. Is there a way to make the name predicable each boot?

**Comment by projektdotnet** [comment]
Forgot to mention it's Arch, kernel version 5.19.9-arch1-1. Intel 12600k, Asus z690-i motherboard.

**Comment by aleksamagicka** [comment]
From the viewpoint of the driver, no, there isn't. We don't control when we get loaded, only that it must happen after the HID bus.

However, I found [this blog post](https://joonas.fi/2021/07/stable-device-path-for-linux-hwmon-interfaces/), perhaps you'll find it useful.

**Comment by projektdotnet** [comment]
That appears to be just what I need, thank you so much!

**Comment by Techwolf** [comment]
I have the same problem with KDE System Monitor. Can this be re-opened and fixed?

**Comment by aleksamagicka** [comment]
As I wrote in https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/issues/40#issuecomment-1250233049, there's nothing that can be done from within the driver - it does not control when it's being loaded. You can look at the instructions at the linked post in that comment, maybe it helps your case.
