### ISSUE TITLE
Support for Power Adjust (3)

### ISSUE THREAD

**Issue by itouchdennis** [aleksamagicka/aquacomputer_d5next-hwmon#57]
Hi there!
I would like to ask for support the power adjust 3 (temp sensor) from aquacomputer. 

Currently I use EndeavourOS and can see the sensor, but it seems like its stuck on 27.8 degrees.

**Comment by aleksamagicka** [comment]
Hi! Power Adjust 3 is not explicitly supported, so if you're seeing sensors from this driver, then it's probably reusing the product ID of an another device.

Can you please share the `sensors` and `lsusb` output?

**Comment by itouchdennis** [comment]
Hi, sure!

###
Sensors:
sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +27.0°C  (high = +80.0°C, crit = +100.0°C)
Core 4:        +26.0°C  (high = +80.0°C, crit = +100.0°C)
Core 8:        +26.0°C  (high = +80.0°C, crit = +100.0°C)
Core 12:       +26.0°C  (high = +80.0°C, crit = +100.0°C)
Core 16:       +28.0°C  (high = +80.0°C, crit = +100.0°C)
Core 20:       +23.0°C  (high = +80.0°C, crit = +100.0°C)
Core 28:       +27.0°C  (high = +80.0°C, crit = +100.0°C)
Core 29:       +27.0°C  (high = +80.0°C, crit = +100.0°C)
Core 30:       +27.0°C  (high = +80.0°C, crit = +100.0°C)
Core 31:       +27.0°C  (high = +80.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +105.0°C)

nct6687-isa-0a20
Adapter: ISA adapter
+12V:           12.26 V  (min = +12.26 V, max = +12.29 V)
+5V:             4.98 V  (min =  +4.97 V, max =  +4.99 V)
+3.3V:           3.37 V  (min =  +3.37 V, max =  +3.38 V)
CPU Soc:       620.00 mV (min =  +0.59 V, max =  +1.01 V)
CPU Vcore:     680.00 mV (min =  +0.68 V, max =  +0.68 V)
CPU 1P8:         0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU VDDP:        0.00 V  (min =  +0.00 V, max =  +0.00 V)
DRAM:            1.23 V  (min =  +1.19 V, max =  +2.00 V)
Chipset:       826.00 mV (min =  +0.83 V, max =  +0.83 V)
CPU SA:        900.00 mV (min =  +0.90 V, max =  +0.90 V)
Voltage #2:      1.52 V  (min =  +1.52 V, max =  +1.52 V)
AVCC3:           3.35 V  (min =  +3.34 V, max =  +3.36 V)
AVSB:            3.37 V  (min =  +3.37 V, max =  +3.38 V)
VBat:            1.06 V  (min =  +1.06 V, max =  +1.06 V)
CPU Fan:       1403 RPM  (min =    0 RPM, max = 1546 RPM)
Pump Fan:         0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #1:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #2:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #3: 1840 RPM  (min = 1832 RPM, max = 2649 RPM)
System Fan #4:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #5:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #6:    0 RPM  (min =    0 RPM, max =    0 RPM)
CPU:            +31.0°C  (low  = +28.5°C, high = +38.0°C)
System:         +37.0°C  (low  = +36.5°C, high = +38.0°C)
VRM MOS:        +34.0°C  (low  = +33.5°C, high = +36.5°C)
PCH:            +52.0°C  (low  = +52.0°C, high = +53.0°C)
CPU Socket:     +32.5°C  (low  = +32.0°C, high = +34.0°C)
PCIe x1:        +35.5°C  (low  = +35.0°C, high = +35.5°C)
M2_1:           +31.5°C  (low  = +31.0°C, high = +32.0°C)

nvme-pci-0200
Adapter: PCI adapter
Composite:    +39.9°C  (low  = -273.1°C, high = +76.8°C)
                       (crit = +78.8°C)
Sensor 1:     +39.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +40.9°C  (low  = -273.1°C, high = +65261.8°C)
####

lsusb:
####
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 013: ID 0c45:636d Microdia PC-LM1E
Bus 001 Device 011: ID 0b05:186e ASUSTek Computer, Inc. ROG Gaming Display Aura Device
Bus 001 Device 010: ID 05e3:0610 Genesys Logic, Inc. Hub
Bus 001 Device 016: ID 194f:0303 PreSonus Audio Electronics, Inc. AudioBox USB 96
Bus 001 Device 015: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 014: ID 090c:1000 Silicon Motion, Inc. - Taiwan (formerly Feiya Technology Corp.) Flash Drive
Bus 001 Device 012: ID 04d9:a292 Holtek Semiconductor, Inc. OBINS
AnnePro2
Bus 001 Device 009: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub             
Bus 001 Device 007: ID 046d:c547 Logitech, Inc. USB Receiver
Bus 001 Device 005: ID 3188:1000 XF HDMI Capture
Bus 001 Device 003: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 002: ID 1462:7d25 Micro Star International MYSTIC LIGHT 
Bus 001 Device 008: ID 0c70:f0bd MCT Elektronikladen poweradjust 3.0
Bus 001 Device 006: ID 1b1c:0c0b Corsair Lighting Node Pro
Bus 001 Device 004: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
#####

maybe also interesting:

sudo dmesg | grep Aqua
[    2.442747] usb 1-13.3: Manufacturer: Aqua Computer
[    2.877759] hid-generic 0003:0C70:F0BD.0006: hiddev99,hidraw5: USB HID v1.01 Device [Aqua Computer poweradjust 3.0] on usb-0000:00:14.0-13.3/input0


Have a nice day and thx for the reply!

**Comment by aleksamagicka** [comment]
OK, for future reference its product ID is `f0bd`.

I'm not sure what temp you are referring to, the device is bound to the `hid-generic` driver which doesn't contribute anything towards showing it in `sensors`.

From the manual, I see that it has a temp sensor and a flow sensor. If you wish to help add support for your device, you'll need to capture some of the HID reports it should be sending every second (all currently supported devices except for one do that) which has the current sensor info. You'd also need to note the current values at the time of capture so that I can correlate them and properly implement it.

It shouldn't be too hard if you haven't done this before! If you wish, I can send you a link to a tutorial for that. And of course, I'm here for any questions.

**Comment by itouchdennis** [comment]
Nevermind, I tought the temp1 (ACPI device) was the temp sensor, so its currently not even shown in the sensor tab - good to know it`s not that one. 
Anyway, if you could send me the link for the tutorial, I will try my best to figure out how I can send you the data for this device. I am not sure how I will be able to get the correct values of the temp sensor, while I am on Linux as the sensor is not showing me the values outside of the OS, but maybe its also included in the tutorial. Otherwise I could try to add a second temp sensor in the loop which shows me the temps on an analog display e.g. or similair.

Thanks for your time!

**Comment by aleksamagicka** [comment]
[Here](https://github.com/liquidctl/liquidctl/blob/main/docs/developer/capturing-usb-traffic.md) it is. For you, the filter should be `usb.idVendor == 0x0c70 && usb.idProduct == 0xf0bd`. If you know your way around Wireshark you may be able to capture those from Linux directly, since you don't need to change settings. Look for a HID report that's sent every second, it should always have the same size.

As this seems to be quite a small device, I believe that the status HID report shouldn't be too long and that I'll be able to find/guess where the temp sensor is. Or, if you happen to use a Windows VM, you can install Aquasuite and confirm the value from there.

**Comment by itouchdennis** [comment]
Thx!
I will give it a try! Windows VM and aquasuite should be easy for tracking the temps.
I will keep you up to date

**Comment by itouchdennis** [comment]
Actually I currently not seeing any every second updating traffic for the filter USB device 8  (usb.device_address == 8) which is the device behind usb.idVendor == 0x0c70 && usb.idProduct == 0xf0bd. Currently I only see some requests and response configuration, no frequently updating temps.
I currently didnt set up a windows VM which I would try these days, I assume, that the temp sensor dont send data when no software try to talk with them. 

Attached the wireshark output. As soon I have set up the VM I will check the output again.

[wireshark_usb.idVendor.zip](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/files/10201277/wireshark_usb.idVendor.zip)

**Comment by aleksamagicka** [comment]
Thanks. AFAICS the `USB_INTERRUPT IN` packets of length 77 are those sensor reports, and the HID payload they carry looks like this:

- `00 00 01 00 00 00 00 00 01 93 40 00 00`
- `00 00 00 00 01 00 00 00 01 93 40 00 00`
- `00 00 00 00 FF FF 00 00 01 93 40 00 00`

The first few bytes change, and the others do not seem to. Looking at the `01 93 40 00` values in a hex editor nets these possible values:

- In big endian: `403`, `37696`, `16384`
- In little endian: `37633`, `16531`.

I'll have to see a Win VM capture to confirm or deny, and what Aquasuite is saying. It's sending something, but it isn't changing much, so at this point I can't say anything definite.

**Comment by itouchdennis** [comment]
Hi!

Windows VM output attached, you can filter it by usb.device_address == 2

Now there are some more traces in there which seems to be the requests from aquasuite for the temps :)

Temps where flapping around 26.8 C (starting from the catpure) and 26.7C  (some sconds after the capture)

Should I start some load at the system to increase the temps? Do you need the temp timestamp in a more detailed version over a longer timespan?
[wireshark_windows_output_poweradjust3.zip](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/files/10202432/wireshark_windows_output_poweradjust3.zip)

**Comment by aleksamagicka** [comment]
Thanks. I think I've found the temp sensor offset (`0x03`). Can you please try the [poweradjust3-support](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/tree/poweradjust3-support) branch and report back if it works, or crashes, or gives bad output?

**Comment by itouchdennis** [comment]
THX for the quick work, the first look is good, it seems to work!

A poweradjust sensor is now listed in the sensors output:

```
$ sensors
poweradjust3-hid-3-6
Adapter: HID adapter
External sensor:  +26.8°C  
[....]

```

jfyi the build process gives me the output:

`$ make dev
make clean
make[1]: Entering directory '/home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support'
make -C /lib/modules/6.0.12-zen1-1-zen/build M=$PWD clean
make[2]: Entering directory '/usr/lib/modules/6.0.12-zen1-1-zen/build'
make[2]: Leaving directory '/usr/lib/modules/6.0.12-zen1-1-zen/build'
make[1]: Leaving directory '/home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support'
make
make[1]: Entering directory '/home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support'
make -C /lib/modules/6.0.12-zen1-1-zen/build M=$PWD modules
make[2]: Entering directory '/usr/lib/modules/6.0.12-zen1-1-zen/build'
  CC [M]  /home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support/aquacomputer_d5next.o
  MODPOST /home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support/Module.symvers
  CC [M]  /home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support/aquacomputer_d5next.mod.o
  LD [M]  /home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support/aquacomputer_d5next.ko
  BTF [M] /home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support/aquacomputer_d5next.ko
make[2]: Leaving directory '/usr/lib/modules/6.0.12-zen1-1-zen/build'
make[1]: Leaving directory '/home/datesli/Documents/aquacomputer_d5next-hwmon-poweradjust3-support'
sudo rmmod aquacomputer_d5next || true
rmmod: ERROR: Module aquacomputer_d5next is not currently loaded
sudo insmod aquacomputer_d5next.ko`

**Comment by aleksamagicka** [comment]
Great, thanks for testing!

The output is completely normal, the error is due to the driver not being in the running kernel already. As long as it exited normally and without errors, it's all fine.

**Comment by itouchdennis** [comment]
Hi again,

It seems like it all works, I have just a quick question, as I am not very familiar with custom mods currently. 
Do you may have a short hint for me, how I add the module to the kernel, so its available at start?  After compiling, the module is loaded and listed via lsmod, on reboot its gone,  the lib still exists on /lib/modules/6.0.12-zen1-1-zen/updates/dkms/aquacomputer_d5next.ko.zst do I may have to run mkinitcpio to rebuild the kernel? Sorry for the maybe dumb question - I just dont want to crash my installation as its currently running so well

**Comment by aleksamagicka** [comment]
TBH I haven't had experience with that, but this looks like it might work: [link](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/kernel_administration_guide/chap-documentation-kernel_administration_guide-working_with_kernel_modules#sec-Loading-kernel-modules-automatically-at-system-boot-time). I think that just putting the `.ko` there is fine.

**Comment by leoratte** [comment]
The module loaded with `make dev` is only temporary. The module you found on your system was probably install with [aquacomputer_d5next-hwmon-dkms](https://aur.archlinux.org/packages/aquacomputer_d5next-hwmon-dkms) from the aur. This package uses the main branch with has no support for your poweradjust3 yet.

**Comment by itouchdennis** [comment]
Ah yes, that was it - alright, I`ll put the build dev command to a temporary autostart script and waiting for the official package.

**Comment by aleksamagicka** [comment]
You can go to #58, click on Customize in the Notifications on the right, select Custom and check `Merged`, so that you'll be notified when it hits the main branch.
