### ISSUE TITLE
Power Adjust 3 after Update not working

### ISSUE THREAD

**Issue by itouchdennis** [aleksamagicka/aquacomputer_d5next-hwmon#63]
Hi there!

First: Thanks for merging the Aquacomputer Power Adjust MR!
I just got the early MR without refactoring locally installed on my PC, on this "release" the Sensor is correctly shown.
If I uninstalled the manually packed package and installed the current release package via AUR instead, the sensor is not shown.

I reverted the changes locally, but it would be great if the new release would work as well as the early MR :)

PS:
Nearly merry X-Mas and thank you for your work!!!

**Comment by aleksamagicka** [comment]
Thanks for the report. I'm sorry you're having this issue and I'll look into it. The Aquastream XT worked after the refactor, and I didn't notice anything weird in the code then so I assumed this was fine as well.

To confirm, the whole device is not showing up in sensors?

**Comment by itouchdennis** [comment]
Might be just a issue at my installation - I uninstalled the package again and did a CLEAN PACKAGE build on AUR, now the sensor is shown up and seems to work, I guess this issue can be closed. Thank you!! :)

**Comment by aleksamagicka** [comment]
Well, that's a relief. Thanks for the quick response. I was already looking at the second commit of #58, since that's the actual refactoring, and couldn't find anything out of order.

Please feel free to report if anything else looks suspicious.

PS. Merry early Xmas to you as well! 😄
