### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by DrTron** [aleksamagicka/aquacomputer_d5next-hwmon#66]
All,

I wonder if we can do something about the naming convention in the output of this module.
In lm_sensors, my aquaero shows as:
`aquaero-hid-3-1cd2`

That is unfortunate as
a) the dashes wreak havoc on any json parsing tool (jq, for instance) when trying to extract values. Underscores do not have that problem.
b) for some reason, the last number changes occasionally. That also challenges json parsing of the data.

The "name" file in /sys/class/hwmon/ just shows "aquaero", so I'm not sure where the rest is coming from.

**Comment by aleksamagicka** [comment]
`aquaero-hid-3-1cd2` is what lm_sensors refers to as [chip name](https://github.com/lm-sensors/lm-sensors/blob/master/lib/data.c#L62). The first number after `hid` should be the number of the HID bus and the hex after is chip address (from [the code](https://github.com/lm-sensors/lm-sensors/blob/master/lib/data.c#L200)).

As you've noticed, the only thing that the driver itself provides is the `aquaero` name. The rest is up to lm_sensors in userspace.

Something similar has been asked in #40, but the link from there probably does not help you, since you read from the `sensors` output and not from hwmon itself.

**Comment by aleksamagicka** [comment]
As for jq, it also works with dashes:

```bash
sensors -j | jq '.["d5next-hid-3-b"]'
```

This returns the data for the D5 Next (or anything else from the JSON that you select):

```json
{
  "Adapter": "HID adapter",
  "Pump voltage": {
    "in0_input": 12.070
  },
  "Fan voltage": {
    "in1_input": 12.090
  },
  "+5V voltage": {
    "in2_input": 4.990
  },
  "+12V voltage": {
    "in3_input": 12.090
  },
  "Pump speed": {
    "fan1_input": 1977.000
  },
  "Fan speed": {
    "fan2_input": 365.000
  },
  "Coolant temp": {
    "temp1_input": 23.240
  },
  "Pump power": {
    "power1_input": 2.630
  },
  "Fan power": {
    "power2_input": 0.380
  },
  "Pump current": {
    "curr1_input": 0.218
  },
  "Fan current": {
    "curr2_input": 0.032
  }
}
```

You can also select anything that starts with `d5`, like so:

```bash
sensors -j | jq 'to_entries[] | select(.key|startswith("d5"))'
```

That returns the key, as well as the value:

```json
{
  "key": "d5next-hid-3-b",
  "value": {
    "Adapter": "HID adapter",
    "Pump voltage": {
      "in0_input": 12.080
    },
    "Fan voltage": {
      "in1_input": 12.100
    },
    "+5V voltage": {
      "in2_input": 4.990
    },
    "+12V voltage": {
      "in3_input": 12.100
    },
    "Pump speed": {
      "fan1_input": 1972.000
    },
    "Fan speed": {
      "fan2_input": 365.000
    },
    "Coolant temp": {
      "temp1_input": 23.270
    },
    "Pump power": {
      "power1_input": 2.640
    },
    "Fan power": {
      "power2_input": 0.380
    },
    "Pump current": {
      "curr1_input": 0.219
    },
    "Fan current": {
      "curr2_input": 0.032
    }
  }
}
```

**Comment by DrTron** [comment]
You're right, I was mostly confused by the changing name, and that definitively was lm_sensors doing it.

But yes, reading directly from hwmon is definitively easier, in spite of requiring some math, no idea why I didn't think of that before. Thanks for the hint!

**Comment by aleksamagicka** [comment]
Great! I'll be sure to include this topic in my future docs rewrite.
