### ISSUE TITLE
6.1.7.arch1-1 seems to break DKMS

### ISSUE THREAD

**Issue by itouchdennis** [aleksamagicka/aquacomputer_d5next-hwmon#67]
Hi!

I just noticed after updating to 6.1.7.arch1-1-zen Kernel, that the DKMS wouldn`t be installed correct anymore.
I just rolled back to 6.1.6 where all was stable and worked fine :)

If needed, I can test upgrading the kernel and / or getting some logs from the existing snapshot before rollback if it would help.

Have a nice day!
Dennis

**Comment by aleksamagicka** [comment]
The DKMS part is not coming from this repo, nobody has yet contributed it here (including myself, as I haven't found the time to toy with it yet). Also, I've never used Arch, much less the Zen kernel, so I'm not sure if they do something differently.

If you can, please try to install the driver from the github repo on its own, on kernel 6.1.7. To make it easier, you can clone it and run `make dev` to compile and insert it. If that goes well, and you see your devices listed, then the problem most likely lies in the DKMS or some distro config.

**Comment by itouchdennis** [comment]
Thanks! I'll try to build it manually later and post the results.

**Comment by itouchdennis** [comment]
As you expected, the make dev part runs fine on the source code, thank you for the support!
I will try to check the dkms part on detail.
