### ISSUE TITLE
Aquacomputer OCTO unpopulated fanheader flapping

### ISSUE THREAD

**Issue by huceke** [aleksamagicka/aquacomputer_d5next-hwmon#7]
The driver works nice for the Aquacomputer OCTO. There is one issue that the Fan voltage reading flaps betwen 0V and 12.04V when the is no fan connected to that header. In my setup i have fanheader 0 - 6 connected and fanheader 7-8 not connected. fanheader 7-8 are flapping constant.

**Comment by aleksamagicka** [comment]
In my testing, that happens when you have those fan headers unpopulated,
but configured to a non zero PWM value so the device tries to control them.
That should cause an alarm in aquasuite if I'm not mistaken. I'll try to
confirm later, but that is not an inherent fault of the driver.

**Comment by aleksamagicka** [comment]
Closing this for now as I can't repro anymore. If anyone has new info, leave a comment below.
