### ISSUE TITLE
kernel 6.2.0-23 seems to break module

### ISSUE THREAD

**Issue by DrTron** [aleksamagicka/aquacomputer_d5next-hwmon#79]
All,

while the aquacomputer_d5next module was working perfectly with kernel 6.2.0-20, the latest upgrade to 6.2.0-23 seems to have created an incompatibility of sorts. Not sure if this is known already.

I am on the latest git pull, I can build the module, but inserting it gives an error. dmesg output is:
`[ 9162.502545] aquacomputer_d5next: disagrees about version of symbol hid_unregister_driver`
`[ 9162.502555] aquacomputer_d5next: Unknown symbol hid_unregister_driver (err -22)`
`[ 9162.502586] aquacomputer_d5next: disagrees about version of symbol hid_hw_start`
`[ 9162.502589] aquacomputer_d5next: Unknown symbol hid_hw_start (err -22)`
`[ 9162.502622] aquacomputer_d5next: disagrees about version of symbol __hid_register_driver`
`[ 9162.502625] aquacomputer_d5next: Unknown symbol __hid_register_driver (err -22)`
`[ 9162.502650] aquacomputer_d5next: disagrees about version of symbol hid_hw_stop`
`[ 9162.502652] aquacomputer_d5next: Unknown symbol hid_hw_stop (err -22)`
`[ 9162.502687] aquacomputer_d5next: disagrees about version of symbol hid_hw_open`
`[ 9162.502690] aquacomputer_d5next: Unknown symbol hid_hw_open (err -22)`
`[ 9162.502710] aquacomputer_d5next: disagrees about version of symbol hid_hw_close`
`[ 9162.502713] aquacomputer_d5next: Unknown symbol hid_hw_close (err -22)`
`[ 9162.502754] aquacomputer_d5next: disagrees about version of symbol hid_hw_raw_request`
`[ 9162.502756] aquacomputer_d5next: Unknown symbol hid_hw_raw_request (err -22)`
`[ 9162.502775] aquacomputer_d5next: disagrees about version of symbol hid_open_report`
`[ 9162.502778] aquacomputer_d5next: Unknown symbol hid_open_report (err -22)`

**Comment by aleksamagicka** [comment]
Assuming this is an Ubuntu kernel, works just fine for me on `Linux osboxes 6.2.0-23-generic #23-Ubuntu SMP PREEMPT_DYNAMIC Wed May 17 16:55:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` that I've just set up.

These errors likely stem from the driver binary being compiled for a different kernel version than the one you're running. Try running `make dev` if you haven't already, that conveniently calls `make clean`, compiles and inserts. Is it looking at the correct kernel headers?

**Comment by DrTron** [comment]
Ah, that did it, a simple "make" didn't. Must have been some residual config that was messing things up.
Thanks!

And yes,  Ubuntu.
`Linux version 6.2.0-23-generic (buildd@bos03-amd64-042) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.2.0-17ubuntu1) 12.2.0, GNU ld (GNU Binutils for Ubuntu) 2.40) #23-Ubuntu SMP PREEMPT_DYNAMIC`

**Comment by aleksamagicka** [comment]
Glad to hear it's resolved, thanks.
