### ISSUE TITLE
Support for Flow sensors "mps flow"

### ISSUE THREAD

**Issue by parahaps** [aleksamagicka/aquacomputer_d5next-hwmon#89]
I just picked up an MPS Flow 100. I was wondering if there was anything I could do to help add support to the driver. Any traffic I can try to scrape to help reverse-engineer it?

That would be:
id: 0c70:f003
Vendor: MCT Elektronikladen
Name: MPS

**Comment by aleksamagicka** [comment]
Looks like it has a flow signal, water temperature and external temperature sensor. [Here](https://github.com/liquidctl/liquidctl/blob/main/docs/developer/capturing-usb-traffic.md) is a great tutorial for capturing the HID traffic; in this instance, the filter should be `usb.idVendor == 0x0c70 && usb.idProduct == 0xf003`. There are two possibilites:

- Look for a HID report that's sent from the device every second, it should always have the same size.
- If you don't see any traffic, fire up Aquasuite. Some devices use an older protocol where you have to explicitly request them to send you anything.

Once you have a snapshot (either way), pair it with the Aquasuite output (the values shown there), so I can try to find them in the captured reports and upload it here.

**Comment by leoratte** [comment]
I just added a draft for the highflow usb #90. Both devices have the same usb product id, so we will have to figure out how to distinguish them. 

It looks like there are even more devices that share this usb product id. See this aquasuite screenshot :
![Screenshot_20230831_232415](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/assets/50664201/5169e521-b48f-411f-a608-f1fa5bd7d1ae)

**Comment by aleksamagicka** [comment]
In the absolute best case, they have the same report structure and IDs. Until we get more info/captured reports from the mps devices, highflow usb inclusion will continue the usual way.

**Comment by aleksamagicka** [comment]
@parahaps Can you please try the latest code from this repo? Support for High Flow USB landed in #90, and by the looks of it MPS and the High Flow report the data in the same way, though for now it will be named as `highflow` in `sensors`.

**Comment by parahaps** [comment]
> @parahaps Can you please try the latest code from this repo? Support for High Flow USB landed in #90, and by the looks of it MPS and the High Flow report the data in the same way, though for now it's named as `highflow` in `sensors`.

This did indeed work! Sample output:

highflow-hid-3-1
Adapter: HID adapter
Flow speed [dL/h]:  386 RPM
External temp:          N/A
Internal temp:      +33.9°C

I am unsure of the RPM->dL/h conversion, though, and I wonder if it that will differ based on the model of flowmeter.

Sorry I was slow, I was actually going to try scraping the usb traffic this weekend.

**Comment by aleksamagicka** [comment]
Great, thanks! As for RPM, there is no conversion actually happening, it's all read from the device. The kernel interface only has a few sensor types (such as temp, RPM, voltage, current, etc.) and RPM is the catch-all for flow sensors and the like (it wouldn't make sense to place them under voltage, for example). That's why `[dL/h]` is noted in the sensor name.
