### ISSUE TITLE
Kernel-supplied module not working, but Github one is?

### ISSUE THREAD

**Issue by DrTron** [aleksamagicka/aquacomputer_d5next-hwmon#94]
All,

not really a bug, but it's something I've wondered about and maybe someone can clear that up:

The aquacomputer_d5next module has been part of the current kernel for a while now. That module, however, loads and is active, but does not work. hwmon directories are not created, and "sensors" doesn't see the aquacomputer devices.

On the other hand, if I pull the code from Github and compile it, either directly or with "dkms --force", the resulting module works as expected.

So currently on every kernel update, the kernel-supplied module is present in the modules tree, causing dkms to not re-compile the module. I have to then run "dkms install --force" on the module to build it and then remove the kernel-supplied version from memory and load the new one. That happens both on Debian 12.4 (currently at 6.1.66, I believe) as on Ubuntu 23.10 (6.5.xx kernel). 

So I'm just wondering why that might be.

**Comment by aleksamagicka** [comment]
Just tested on a brand new Ubuntu 23.10 VM and everything's working fine, the D5 Next I passed through is seen immediately.

> hwmon directories are not created, and "sensors" doesn't see the aquacomputer devices.

I'm not sure why this would ever happen. This is the job of the hwmon core, the driver just passes through the USB IDs. I _think_ that the hwmon directory should always get created, but I'm not 100% sure as it's been a while that I've looked at that code.

Can you perhaps test with a live USB, or a VM (depending on what suits your situation)? When did this start happening?

**Comment by aleksamagicka** [comment]
Yup, looks like it's creating it at [init time](https://elixir.bootlin.com/linux/latest/source/drivers/hwmon/hwmon.c#L1172) thanks to the `__init`, which runs once the kernel starts and the `class_register()` call registers a, well, [class](https://elixir.bootlin.com/linux/latest/source/drivers/hwmon/hwmon.c#L140) named `hwmon`.

I don't see why it wouldn't do this every time?

**Comment by DrTron** [comment]
I may need to clarify this a little: the directory /sys/class/hwmon itself is there, and contains other hwmon subdirectories, such as the one for coretemp, etc. So hwmon does get initialized correctly.
Just the ones for the aquacomputer devices are missing. The kernel-supplied module is loaded (as evident by lsmod), but seems to be inactive.
This has started the first time a kernel upgrade included the aquacomputer_d5next module. Before that, it wasn't included and I compiled the module using dkms, which worked fine. Now, of course, dkms notices that there already is a module included in the kernel libraries, and does not compile and load the module anymore.

I'm just a little perplexed as it happens with both systems that have aquacomputer devices.
On another note, I have two more systems running that have a Corsair Commander Pro fan controller, for which also a kernel module exists. Here it was the same situation: kernel module was available on Github, but not shipped with the kernel, and at some upgrade point (likely the move from a 5.xx to a 6.xx kernel in Debian) the kernel had the module. On these systems and with this module, I do not have that issue. The supplied module works fine.

Hope that clarifies it a bit.

**Comment by aleksamagicka** [comment]
The module was first in 5.15, with support for only the D5 Next.

What Aquacomputer devices do you have in those systems? I'm asking to try to pinpoint in which kernel version they showed up for the first time.

**Comment by DrTron** [comment]
IIRC Debian 11 (bullseye) was on 5.10, and then made the jump to 6.1 with Debian 12 (bookworm), so that's likely the timeframe. Not sure about the Ubuntu kernels.
One system (Debian) has an aquaero5, the other (Ubuntu 23.10) an aquaero5LT and an aquastream pump.

**Comment by aleksamagicka** [comment]
> One system (Debian) has an aquaero5

If it's at 6.1, it indeed shouldn't see the Aquaero, support for that landed in 6.3.

> the other (Ubuntu 23.10) an aquaero5LT and an aquastream pump.

The pump would be either 6.3 or 6.4, so they should be seen with 6.5. I'll try with dkms later... out of the box it all works fine AFAICS.

**Comment by aleksamagicka** [comment]
Also, in the words of the hwmon maintainer from a few days ago: `... bus registration code has been changed significantly in v6.3.`

Maybe something happened and the Ubuntu system is not picking the devices as it should? I'm not sure what the changes are as I haven't looked yet, but maybe that will be useful here.

**Comment by DrTron** [comment]
> If it's at 6.1, it indeed shouldn't see the Aquaero, support for that landed in 6.3.

Ah, that might be it. It's loading the module, but the module version shipped with 6.1 doesn't know anything about the aquaero, so nothing comes up. Obviously, when compiling the module with dkms, I use the latest Github pull.

Going by the package repositories it's a 6.1 for the Debian system but a 6.5 for the Ubuntu system, so the latter should know about it already. But I'll check the kernel versions tonight.

**Comment by aleksamagicka** [comment]
Just checking, is this still an issue?
